<?xml version="1.0" encoding="utf-8"?><Database Name="DataAcquisition" Class="AnalysisSystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\SQLEXPRESS;Initial Catalog=DataAcquisition;Integrated Security=True" SettingsObjectName="AnalysisSystem.Properties.Settings" SettingsPropertyName="DataAcquisitionConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DataPoint" Member="DataPoints">
    <Type Name="DataPoint">
      <Column Name="SID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FdArousal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FdValence" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Label" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Sample_DataPoint" Member="Sample" ThisKey="SID" OtherKey="SID" Type="Sample" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EEG" Member="EEGs">
    <Type Name="EEG">
      <Column Name="SID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AF3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F7" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FC5" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="T7" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="P7" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="O1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="O2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="T8" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="P8" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FC6" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F8" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AF4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Sample_EEG" Member="Sample" ThisKey="SID" OtherKey="SID" Type="Sample" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Group">
      <Column Name="GID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Group_PicGroup" Member="PicGroups" ThisKey="GID" OtherKey="GID" Type="PicGroup" />
    </Type>
  </Table>
  <Table Name="dbo.PicGroups" Member="PicGroups">
    <Type Name="PicGroup">
      <Column Name="PID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Group_PicGroup" Member="Group" ThisKey="GID" OtherKey="GID" Type="Group" IsForeignKey="true" />
      <Association Name="Picture_PicGroup" Member="Picture" ThisKey="PID" OtherKey="PID" Type="Picture" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pictures" Member="Pictures">
    <Type Name="Picture">
      <Column Name="PID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Arousal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Valence" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ArousalSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ValenceSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Picture_PicGroup" Member="PicGroups" ThisKey="PID" OtherKey="PID" Type="PicGroup" />
      <Association Name="Picture_VolPic" Member="VolPics" ThisKey="PID" OtherKey="PID" Type="VolPic" />
    </Type>
  </Table>
  <Table Name="dbo.Samples" Member="Samples">
    <Type Name="Sample">
      <Column Name="SID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EdfPath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CsvPath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SamArousal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SamValence" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AffectionLabel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsGood" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Sample_DataPoint" Member="DataPoint" ThisKey="SID" OtherKey="SID" Type="DataPoint" Cardinality="One" />
      <Association Name="Sample_EEG" Member="EEG" ThisKey="SID" OtherKey="SID" Type="EEG" Cardinality="One" />
      <Association Name="Sample_VolPic" Member="VolPics" ThisKey="SID" OtherKey="SID" Type="VolPic" />
    </Type>
  </Table>
  <Table Name="dbo.VolPics" Member="VolPics">
    <Type Name="VolPic">
      <Column Name="VID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Picture_VolPic" Member="Picture" ThisKey="PID" OtherKey="PID" Type="Picture" IsForeignKey="true" />
      <Association Name="Sample_VolPic" Member="Sample" ThisKey="SID" OtherKey="SID" Type="Sample" IsForeignKey="true" />
      <Association Name="Volunteer_VolPic" Member="Volunteer" ThisKey="VID" OtherKey="VID" Type="Volunteer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Volunteers" Member="Volunteers">
    <Type Name="Volunteer">
      <Column Name="VID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Study" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="JobTitle" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Volunteer_VolPic" Member="VolPics" ThisKey="VID" OtherKey="VID" Type="VolPic" />
    </Type>
  </Table>
</Database>